### ISSUE TITLE
regressor-face-pose dependências 

### ISSUE THREAD

**Issue by krymancer** [mari-linhares/tensorflow_brasil#10]
`pip install opencv scikit-learn dlib`
não funciona, `opencv` deve ser referenciado como `opencv-python` para ser instalado pelo `pip` ou o `pip3` ficando da seguinte:
`pip install opencv-python scikit-learn dlib`

saída anterior :
`$: pip install opencv`
`Collecting opencv`
`Could not find a version that satisfies the requirement opencv (from versions: )`
`No matching distribution found for opencv`

**Comment by hereismari** [comment]
Oi Junior,

Fica a vontade pra fazer um PR pra consertar.
